language: go
sudo: false
go: tip

before_install:
  - go get github.com/mattn/goveralls

install:
  - go get ./...

script:
  - go test -v ./... -cover -covermode=count -coverprofile=coverage.out

after_success:
  - $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci

